# Boot Animation Maker config template
#
# Magisk Module output filename
'module_export_filename': 'BootAniMagiskModule.zip'
# Screen size [w x h], use the maximum size
'device_size': [1080, 1920]
# Specify the FPS, it should be matched to gif,
# For animation contains only one part, If it doesn't match, the script will ask if to replace the this FPS with the actual FPS.
# For animation contains more than one part, each gif needs to have the same or similar FPS (diff<=5), the script will use the average of FPS instead，If the difference is too large, stop generating.
'fps': 10
# ******************************************************
# Layer config 'anime'
#                - {part0}
#                - {part1}
#                - {...}
# ******************************************************
'anime':
  - 'gif_path': './example/e1.gif' # gif file path，Absolute path is recommended. if use relative path, the path relatives to the running environment.
    # Image config
    'cpnt_conf':
      # Background (= Screen size)
      'bg_cpnt':
        'bg_color': 'rgba(0,0,0,255)' # background color, 'rgba(r, g, b, a)' or 'auto'(yet not supported)
      # Dynamic component, only contains one gif
      'dyn_cpnt':
        'resize_mode': 'scale' # Resize method, 'scale' or 'trim'
        'target_size': [1080, 1] # target size [w x h]，when use scale, 'w' prevails
        'c_pos': [540, 756] # Central coordinates of gif(Relative to background)
        'on_top': True # The upper and lower relations between dynamic component and static components
      # Static components，this section can contain more than one PNG pictures
      'sta_cpnt': # Layer relationships for static components are determined by order, the image at the bottom of the list is on the top layer.
        - 'im_path': './example/e2.png' # images file path
          'resize_mode': 'scale' # Resize method, 'scale' or 'trim'
          'target_size': [674, 1] # target size [w x h]，when use scale, 'w' prevails
          'c_pos': [540, 956] # Central coordinates of png(Relative to background)
        - 'im_path': './example/e3.png'
          'resize_mode': 'scale'
          'target_size': [320, 1]
          'c_pos': [540, 1700]
    # desc.txt file setting. Description: https://android.googlesource.com/platform/frameworks/base/+/master/cmds/bootanimation/FORMAT.md
    'desc_conf':
      'type': 'p'
      'count': '0'
      'pause': '0'

  - 'gif_path': './example/e4.gif'

    'cpnt_conf':
      'bg_cpnt':
        'bg_color': 'rgba(0,0,0,255)'

      'dyn_cpnt':
        'resize_mode': 'scale'
        'target_size': [1080, 1]
        'c_pos': [540, 756]

      'sta_cpnt':
        - 'im_path': './example/e5.png'
          'resize_mode': 'scale'
          'target_size': [674, 1]
          'c_pos': [540, 956]
        - 'im_path': './example/e6.png'
          'resize_mode': 'scale'
          'target_size': [320, 1]
          'c_pos': [540, 1700]

    'desc_conf':
      'type': 'c'
      'count': '0'
      'pause': '0'

# Magisk module custom setting in module.prop
'module_prop_conf':
  'mid': 'bootanimation-000'
  'name': 'BootAnimation'
  'version': '1.0'
  'versionCode': '2018103101'
  'author': 'Zarcher'
  'description': 'A Boot Animation Magisk Module'

# Magisk module custom setting in install.sh
'module_config_conf':
  'ui_print': 'ui_print "     Boot Animation    "\n'
  'REPLACE': 'REPLACE="\n\n"'

# FOR DEBUG, DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING
'check_gif': True # check the gif FPS setting



